In [1]:
import torch
import torch.nn as nn

In [4]:
# Tensor: matrix or an array, 1d tensor, 2d tensor, 3d tensor, 3x10x20 tensor, etc
# ints or floats
# they carry derivatives under the hood, dont need to do derivatives by hand

a = torch.ones(3,5) # 5x5 tensor of all ones
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
# sum() and mean()

# sum(tensor, axis of dimension)
sum = torch.sum(a, axis=0) # tensor and axis (0 or 1) of dimension. 0 = col, 1 = row
sum

tensor([5.])

In [18]:
# squeeze() and unsqueeze(), used all the time
# unncessary dimension
a = torch.ones(5,1)

# 5,1 => 5x1
# 5, => size 5
# squeeze() squeezes out those any uncessary dimension
print("---------- before squeeze")
print(a.shape)
print(a)
squeezed = torch.squeeze(a)
print("------------ After squeezing")
print(squeezed.shape)
print(squeezed)

print("------------unsqueeze")
unsqueezed = torch.unsqueeze(squeezed, dim = 1) # make it 5x1
print(unsqueezed.shape)

---------- before squeeze
torch.Size([5, 1])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])
------------ After squeezing
torch.Size([5])
tensor([1., 1., 1., 1., 1.])
------------unsqueeze
torch.Size([5, 1])


In [ ]:
# Neural Network Models
#pytorch defines models that are specifically nn
# module, inhirit nn.module

class MyModel:
    # constructor (layers of nn)

    # Forward Method - get_model_prediction(example_datapoint)
    # override forward method, take in ex datapoints, bath data point x
    # use layers of model and other funcs, returning ultimate model precition
    pass

In [ ]:
# torch.nn.Linear(in_features, out_features)
# omplemented the pre defined architecture based on a google image
class MyModel(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.first_layer = nn.Linear(4, 6)
        self.second_layer = nn.Linear(6, 6)
        self.final_layer = nn.Linear(6, 2) # predicts 2 nums

    def forward(self, x):
        # first_layer_output = self.first_layer.forward(x)
        return self.final_layer(self.second_layer.forward(self.first_layer.forward(x)))
    
model = MyModel()

# 1) train model for some number of iterations

# 2) then use the model and get predictions

example_datapoint = torch.randn(1, 4) # 1x4 tensor
#model.forward(example_datapoint) # pass dataponit in from left to right