<a href="https://colab.research.google.com/github/jechea14/leetcode/blob/main/ml_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv('500hits.csv', encoding='latin-1')

In [ ]:
df.head()

PLAYER  YRS     G     AB     R     H   2B   3B   HR   RBI    BB  \
0       Ty Cobb   24  3035  11434  2246  4189  724  295  117   726  1249   
1   Stan Musial   22  3026  10972  1949  3630  725  177  475  1951  1599   
2  Tris Speaker   22  2789  10195  1882  3514  792  222  117   724  1381   
3   Derek Jeter   20  2747  11195  1923  3465  544   66  260  1311  1082   
4  Honus Wagner   21  2792  10430  1736  3430  640  252  101     0   963   

     SO   SB   CS     BA  HOF  
0   357  892  178  0.366    1  
1   696   78   31  0.331    1  
2   220  432  129  0.345    1  
3  1840  358   97  0.310    1  
4   327  722   15  0.329    1

In [ ]:
df = df.drop(columns=['PLAYER', 'CS'])

In [ ]:
X1 = df.iloc[:, 0:13]
X1

YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA
0     24  3035  11434  2246  4189  724  295  117   726  1249   357  892  0.366
1     22  3026  10972  1949  3630  725  177  475  1951  1599   696   78  0.331
2     22  2789  10195  1882  3514  792  222  117   724  1381   220  432  0.345
3     20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358  0.310
4     21  2792  10430  1736  3430  640  252  101     0   963   327  722  0.329
..   ...   ...    ...   ...   ...  ...  ...  ...   ...   ...   ...  ...    ...
460   15  1920   6653  1105  1665  285   39  291   964  1224  1427  225  0.250
461   17  1829   6092   900  1664  379   10  275  1065   936  1453   20  0.273
462   15  1834   6499  1062  1661  338   67  210   761   960  1190  315  0.256
463   16  1822   6309   714  1660  254   25   54   593   396   489   74  0.263
464   15  1468   5629   785  1660  247   71   61   499   266   471  267  0.295

[465 rows x 13 columns]

In [ ]:
X2 = df.iloc[:, 0:13]

# Standardization

In [ ]:
# standardization
scaleStandard = StandardScaler()


In [ ]:
# fit the data with sklearn
X1 = scaleStandard.fit_transform(X1)

In [ ]:
X1 = pd.DataFrame(X1, columns=['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB', 'BA'])

In [ ]:
X1.head()

YRS         G        AB         R         H        2B        3B  \
0  2.516295  2.786078  3.034442  3.787062  4.764193  3.559333  4.389485   
1  1.792237  2.760655  2.677044  2.760530  3.444971  3.569709  1.996457   
2  1.792237  2.091184  2.075964  2.528955  3.171214  4.264876  2.909053   
3  1.068180  1.972543  2.849554  2.670665  3.055576  1.691719 -0.254611   
4  1.430208  2.099658  2.257758  2.024329  2.972977  2.687780  3.517449   

         HR       RBI        BB        SO        SB        BA  
0 -0.585841 -0.346449  1.423013 -1.003628  3.832067  3.648290  
1  1.909487  2.175837  2.493089 -0.309948 -0.649080  1.996159  
2 -0.585841 -0.350567  1.826585 -1.283965  1.299723  2.657012  
3  0.410896  0.858071  0.912434  2.030966  0.892346  1.004881  
4 -0.697364 -1.841290  0.548609 -1.065016  2.896201  1.901752

mean: 0, great can see where data lies

---


std: 1

---


min of ~-2.19 and max of ~3.2 depend on std

In [ ]:
X1.describe().round(3)

YRS        G       AB        R        H       2B       3B       HR  \
count  465.000  465.000  465.000  465.000  465.000  465.000  465.000  465.000   
mean    -0.000    0.000    0.000    0.000    0.000    0.000   -0.000   -0.000   
std      1.001    1.001    1.001    1.001    1.001    1.001    1.001    1.001   
min     -2.190   -2.027   -1.958   -1.899   -1.204   -2.116   -1.532   -1.339   
25%     -0.742   -0.697   -0.765   -0.741   -0.784   -0.715   -0.762   -0.851   
50%     -0.018   -0.157   -0.209   -0.160   -0.222   -0.155   -0.234   -0.161   
75%      0.706    0.560    0.517    0.504    0.483    0.571    0.577    0.634   
max      3.240    3.557    3.754    3.956    4.764    4.265    4.673    3.861   

           RBI       BB       SO       SB       BA  
count  465.000  465.000  465.000  465.000  465.000  
mean     0.000    0.000   -0.000    0.000    0.000  
std      1.001    1.001    1.001    1.001    1.001  
min     -1.841   -1.665   -1.734   -1.040   -2.016  
25%     -0.524   -0.760   -0.842   -0.732   -0.742  
50%      0.152   -0.145   -0.046   -0.324   -0.081  
75%      0.642    0.524    0.775    0.490    0.533  
max      2.888    4.300    3.580    6.662    3.648

# Normalization

In [ ]:
# normalization: 0 to 1
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaleMinMax = MinMaxScaler(feature_range=(0,1))

In [ ]:
X2 = scaleMinMax.fit_transform(X2)

In [ ]:
# create a df for X2
X2 = pd.DataFrame(X2, columns=['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB', 'BA'])

In [ ]:
X2.head()

YRS         G        AB         R         H        2B        3B  \
0  0.866667  0.861912  0.874035  0.971074  1.000000  0.889431  0.954248   
1  0.733333  0.857360  0.811459  0.795750  0.778964  0.891057  0.568627   
2  0.733333  0.737481  0.706217  0.756198  0.733096  1.000000  0.715686   
3  0.600000  0.716237  0.841663  0.780401  0.713721  0.596748  0.205882   
4  0.666667  0.738998  0.738047  0.670012  0.699881  0.752846  0.813725   

         HR       RBI        BB        SO        SB        BA  
0  0.144772  0.316064  0.517683  0.137466  0.632595  1.000000  
1  0.624665  0.849369  0.697078  0.268002  0.050751  0.708333  
2  0.144772  0.315194  0.585341  0.084713  0.303788  0.825000  
3  0.336461  0.570744  0.432086  0.708510  0.250893  0.533333  
4  0.123324  0.000000  0.371092  0.125915  0.511079  0.691667

In [ ]:
X2.describe().round(3)

YRS        G       AB        R        H       2B       3B       HR  \
count  465.000  465.000  465.000  465.000  465.000  465.000  465.000  465.000   
mean     0.403    0.363    0.343    0.324    0.202    0.332    0.247    0.257   
std      0.184    0.179    0.175    0.171    0.168    0.157    0.161    0.193   
min      0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000   
25%      0.267    0.238    0.209    0.198    0.070    0.220    0.124    0.094   
50%      0.400    0.335    0.306    0.297    0.164    0.307    0.209    0.227   
75%      0.533    0.463    0.433    0.410    0.283    0.421    0.340    0.379   
max      1.000    1.000    1.000    1.000    1.000    1.000    1.000    1.000   

           RBI       BB       SO       SB       BA  
count  465.000  465.000  465.000  465.000  465.000  
mean     0.389    0.279    0.326    0.135    0.356  
std      0.212    0.168    0.188    0.130    0.177  
min      0.000    0.000    0.000    0.000    0.000  
25%      0.279    0.152    0.168    0.040    0.225  
50%      0.421    0.255    0.318    0.093    0.342  
75%      0.525    0.367    0.472    0.199    0.450  
max      1.000    1.000    1.000    1.000    1.000

In [ ]:
X1.describe().round(3)

YRS        G       AB        R        H       2B       3B       HR  \
count  465.000  465.000  465.000  465.000  465.000  465.000  465.000  465.000   
mean    -0.000    0.000    0.000    0.000    0.000    0.000   -0.000   -0.000   
std      1.001    1.001    1.001    1.001    1.001    1.001    1.001    1.001   
min     -2.190   -2.027   -1.958   -1.899   -1.204   -2.116   -1.532   -1.339   
25%     -0.742   -0.697   -0.765   -0.741   -0.784   -0.715   -0.762   -0.851   
50%     -0.018   -0.157   -0.209   -0.160   -0.222   -0.155   -0.234   -0.161   
75%      0.706    0.560    0.517    0.504    0.483    0.571    0.577    0.634   
max      3.240    3.557    3.754    3.956    4.764    4.265    4.673    3.861   

           RBI       BB       SO       SB       BA  
count  465.000  465.000  465.000  465.000  465.000  
mean     0.000    0.000   -0.000    0.000    0.000  
std      1.001    1.001    1.001    1.001    1.001  
min     -1.841   -1.665   -1.734   -1.040   -2.016  
25%     -0.524   -0.760   -0.842   -0.732   -0.742  
50%      0.152   -0.145   -0.046   -0.324   -0.081  
75%      0.642    0.524    0.775    0.490    0.533  
max      2.888    4.300    3.580    6.662    3.648

# One Hot Encoder

In [ ]:
# one hot encoder: used when working with categorical data
# transform categorical
# nominal data: cate data without numeric difference (colors)
from sklearn.preprocessing import OneHotEncoder

In [ ]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000], 'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'], 'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [ ]:
df = pd.DataFrame(data=d)

In [ ]:
df.head()

sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [ ]:
# choose data that doesnt have numeric difference
# city, doesnt have numeric difference
df['city'].unique()

array(['Tampa', 'Orlando', 'Jacksonville', 'Miami'], dtype=object)

In [ ]:
# one hot encoder expands the table with the cities, change cities within pandas df
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform='pandas')

In [ ]:
ohetransform = ohe.fit_transform(df[['city']])

In [ ]:
ohetransform
# first data is tampa, 2nd is tampa, 3rd is orlando,
# abc order automatically

city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           0.0         1.0
2                 0.0         0.0           1.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         1.0           0.0         0.0
5                 1.0         0.0           0.0         0.0
6                 0.0         1.0           0.0         0.0
7                 0.0         1.0           0.0         0.0
8                 0.0         0.0           1.0         0.0
9                 0.0         0.0           1.0         0.0
10                0.0         0.0           1.0         0.0
11                0.0         0.0           1.0         0.0

In [ ]:
df.head()

sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [ ]:
ohetransform.head()

city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                0.0         0.0           0.0         1.0
1                0.0         0.0           0.0         1.0
2                0.0         0.0           1.0         0.0
3                1.0         0.0           0.0         0.0
4                0.0         1.0           0.0         0.0

In [ ]:
# merge df with ohetransform
df = pd.concat([df, ohetransform], axis=1).drop(columns=['city'])

In [ ]:
df.head(10)

sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0   100000   Small                0.0         0.0           0.0         1.0
1   222000  Medium                0.0         0.0           0.0         1.0
2  1000000   Large                0.0         0.0           1.0         0.0
3   522000   Large                1.0         0.0           0.0         0.0
4   111111   Small                0.0         1.0           0.0         0.0
5   222222  Medium                1.0         0.0           0.0         0.0
6  1111111   Large                0.0         1.0           0.0         0.0
7    20000   Small                0.0         1.0           0.0         0.0
8    75000  Medium                0.0         0.0           1.0         0.0
9    90000  Medium                0.0         0.0           1.0         0.0

# Ordinal Encoder

transforms ordinal data (inherit ranking like size) into numerical data like 0 for small, 1 for med, 2 for large

In [ ]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000], 'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'], 'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}
df = pd.DataFrame(data=d)

In [ ]:
df.head()

sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [ ]:
# sales for difference stores and cities
# categorical data, ordinal(inherit ranking): size, nominal(no inherit ranking): city

#specify order
df['size'].unique()

array(['Small', 'Medium', 'Large'], dtype=object)

In [ ]:
sizes = ['Small', 'Medium', 'Large']

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
# allows small for first, med for second, large for third. dont want to be in abc order
enc = OrdinalEncoder(categories=[sizes])

In [ ]:
enc.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.]])

In [ ]:
df.head()

sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [ ]:
df['size'] = enc.fit_transform(df[['size']])

In [ ]:
df.head()

sales          city  size
0   100000         Tampa   0.0
1   222000         Tampa   1.0
2  1000000       Orlando   2.0
3   522000  Jacksonville   2.0
4   111111         Miami   0.0

# Simple Imputer
- fill in null values in pandas df
- most ml models don't allow null values so simple imputer is a good way to fix that
- mode, mean, median

In [ ]:
import numpy as np

In [ ]:
miles = pd.DataFrame({'farthest_run_mi': [50,62,np.nan,100,26,13,31,50]})

In [ ]:
miles

farthest_run_mi
0             50.0
1             62.0
2              NaN
3            100.0
4             26.0
5             13.0
6             31.0
7             50.0

In [ ]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imp_mean = SimpleImputer(strategy='mean') # most commonly used, depending on where data lies

In [ ]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

median

In [ ]:
imp_median = SimpleImputer(strategy='median')

In [ ]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

Mode
- can also be used for categorical data

In [ ]:
imp_mode = SimpleImputer(strategy='most_frequent')
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

constant

In [ ]:
imp_constant = SimpleImputer(strategy='constant', fill_value=13)
imp_constant.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

Categorical

In [ ]:
names = pd.DataFrame({'names': ['ryan', 'nolan', 'honus', 'wagner', np.nan, 'ruth']})

In [ ]:
names

names
0    ryan
1   nolan
2   honus
3  wagner
4     NaN
5    ruth

In [ ]:
imp_constant_category = SimpleImputer(strategy='constant', fill_value='babe')

In [ ]:
imp_constant_category.fit_transform(names)

array([['ryan'],
       ['nolan'],
       ['honus'],
       ['wagner'],
       ['babe'],
       ['ruth']], dtype=object)

show imputed

In [ ]:
# add brand new column of 0s and 1s of what values were imputed
imp_mean_marked = SimpleImputer(strategy='mean', add_indicator=True)

In [ ]:
imp_mean_marked.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 47.42857143,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

More complicated example

In [ ]:
df = pd.DataFrame({'Name': ['Ryan', 'Nolan', 'Walter', 'Honus', 'Christy', np.nan, 'Napolean', 'Tris'],
                   'farthest_run_mi': [50,62,np.nan,100,26,13,31,50]})

In [ ]:
df

Name  farthest_run_mi
0      Ryan             50.0
1     Nolan             62.0
2    Walter              NaN
3     Honus            100.0
4   Christy             26.0
5       NaN             13.0
6  Napolean             31.0
7      Tris             50.0

In [ ]:
# make column transformer
from sklearn.compose import make_column_transformer

In [ ]:
ct = make_column_transformer(
    (imp_constant_category, ['Name']),
    (imp_mean, ['farthest_run_mi']),
    remainder='drop'

)

In [ ]:
ct.set_output(transform='pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='babe',
                                               strategy='constant'),
                                 ['Name']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['farthest_run_mi'])])

In [ ]:
df_pandas = ct.fit_transform(df)

In [ ]:
df_pandas

simpleimputer-1__Name  simpleimputer-2__farthest_run_mi
0                  Ryan                         50.000000
1                 Nolan                         62.000000
2                Walter                         47.428571
3                 Honus                        100.000000
4               Christy                         26.000000
5                  babe                         13.000000
6              Napolean                         31.000000
7                  Tris                         50.000000

# Column Transformer

In [ ]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000], 'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'], 'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}
df = pd.DataFrame(data=d)

In [ ]:
df

sales          city    size
0    100000         Tampa   Small
1    222000         Tampa  Medium
2   1000000       Orlando   Large
3    522000  Jacksonville   Large
4    111111         Miami   Small
5    222222  Jacksonville  Medium
6   1111111         Miami   Large
7     20000         Miami   Small
8     75000       Orlando  Medium
9     90000       Orlando  Medium
10  1000000       Orlando  Medium
11    10000       Orlando   Small

In [ ]:
# one hot encoder
# ordinal encoder
ohe = OneHotEncoder(sparse_output=False)
ode = OrdinalEncoder()

In [ ]:
# import make column transformer

ct = make_column_transformer(
    # one hot encoder, column to implement
    (ohe, ['city']),
    # ordinal encoder,
    (ode, ['size']),
    # what happens with the remaining cols, passthrough if you want to keep cols
    remainder = 'passthrough'
)

In [ ]:
ct.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), ['city']),
                                ('ordinalencoder', OrdinalEncoder(), ['size'])])

In [ ]:
df_pandas = ct.fit_transform(df)

In [ ]:
df_pandas

onehotencoder__city_Jacksonville  onehotencoder__city_Miami  \
0                                0.0                        0.0   
1                                0.0                        0.0   
2                                0.0                        0.0   
3                                1.0                        0.0   
4                                0.0                        1.0   
5                                1.0                        0.0   
6                                0.0                        1.0   
7                                0.0                        1.0   
8                                0.0                        0.0   
9                                0.0                        0.0   
10                               0.0                        0.0   
11                               0.0                        0.0   

    onehotencoder__city_Orlando  onehotencoder__city_Tampa  \
0                           0.0                        1.0   
1                           0.0                        1.0   
2                           1.0                        0.0   
3                           0.0                        0.0   
4                           0.0                        0.0   
5                           0.0                        0.0   
6                           0.0                        0.0   
7                           0.0                        0.0   
8                           1.0                        0.0   
9                           1.0                        0.0   
10                          1.0                        0.0   
11                          1.0                        0.0   

    ordinalencoder__size  remainder__sales  
0                    2.0            100000  
1                    1.0            222000  
2                    0.0           1000000  
3                    0.0            522000  
4                    2.0            111111  
5                    1.0            222222  
6                    0.0           1111111  
7                    2.0             20000  
8                    1.0             75000  
9                    1.0             90000  
10                   1.0           1000000  
11                   2.0             10000

In [ ]:
# drop
ct2 = make_column_transformer(
    # one hot encoder, column to implement
    (ohe, [1]),
    # ordinal encoder,
    (ode, [2]),
    # what happens with the remaining cols, passthrough
    remainder = 'drop'
)

In [ ]:
ct2.set_output(transform='pandas')

ColumnTransformer(transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), [1]),
                                ('ordinalencoder', OrdinalEncoder(), [2])])

In [ ]:
df_pandas2 = ct2.fit_transform(df)

In [ ]:
df_pandas2

onehotencoder__city_Jacksonville  onehotencoder__city_Miami  \
0                                0.0                        0.0   
1                                0.0                        0.0   
2                                0.0                        0.0   
3                                1.0                        0.0   
4                                0.0                        1.0   
5                                1.0                        0.0   
6                                0.0                        1.0   
7                                0.0                        1.0   
8                                0.0                        0.0   
9                                0.0                        0.0   
10                               0.0                        0.0   
11                               0.0                        0.0   

    onehotencoder__city_Orlando  onehotencoder__city_Tampa  \
0                           0.0                        1.0   
1                           0.0                        1.0   
2                           1.0                        0.0   
3                           0.0                        0.0   
4                           0.0                        0.0   
5                           0.0                        0.0   
6                           0.0                        0.0   
7                           0.0                        0.0   
8                           1.0                        0.0   
9                           1.0                        0.0   
10                          1.0                        0.0   
11                          1.0                        0.0   

    ordinalencoder__size  
0                    2.0  
1                    1.0  
2                    0.0  
3                    0.0  
4                    2.0  
5                    1.0  
6                    0.0  
7                    2.0  
8                    1.0  
9                    1.0  
10                   1.0  
11                   2.0

In [ ]:
# drop certain cols
ct3 = make_column_transformer(
    # one hot encoder, column to implement
    (ohe, ['city']),
    # ordinal encoder,
    ('passthrough', ['size']),
    # what happens with the remaining cols, passthrough
    remainder = 'drop'
)

In [ ]:
ct3.set_output(transform='pandas')

ColumnTransformer(transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), ['city']),
                                ('passthrough', 'passthrough', ['size'])])

In [ ]:
df_pandas3 = ct3.fit_transform(df)

In [ ]:
df_pandas3

onehotencoder__city_Jacksonville  onehotencoder__city_Miami  \
0                                0.0                        0.0   
1                                0.0                        0.0   
2                                0.0                        0.0   
3                                1.0                        0.0   
4                                0.0                        1.0   
5                                1.0                        0.0   
6                                0.0                        1.0   
7                                0.0                        1.0   
8                                0.0                        0.0   
9                                0.0                        0.0   
10                               0.0                        0.0   
11                               0.0                        0.0   

    onehotencoder__city_Orlando  onehotencoder__city_Tampa passthrough__size  
0                           0.0                        1.0             Small  
1                           0.0                        1.0            Medium  
2                           1.0                        0.0             Large  
3                           0.0                        0.0             Large  
4                           0.0                        0.0             Small  
5                           0.0                        0.0            Medium  
6                           0.0                        0.0             Large  
7                           0.0                        0.0             Small  
8                           1.0                        0.0            Medium  
9                           1.0                        0.0            Medium  
10                          1.0                        0.0            Medium  
11                          1.0                        0.0             Small

# k nearest neighbors

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# analyze results
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

Code the model

In [ ]:
# code out the model
df = pd.read_csv('500hits.csv', encoding='latin-1')

In [ ]:
df.head()

PLAYER  YRS     G     AB     R     H   2B   3B   HR   RBI    BB  \
0       Ty Cobb   24  3035  11434  2246  4189  724  295  117   726  1249   
1   Stan Musial   22  3026  10972  1949  3630  725  177  475  1951  1599   
2  Tris Speaker   22  2789  10195  1882  3514  792  222  117   724  1381   
3   Derek Jeter   20  2747  11195  1923  3465  544   66  260  1311  1082   
4  Honus Wagner   21  2792  10430  1736  3430  640  252  101     0   963   

     SO   SB   CS     BA  HOF  
0   357  892  178  0.366    1  
1   696   78   31  0.331    1  
2   220  432  129  0.345    1  
3  1840  358   97  0.310    1  
4   327  722   15  0.329    1

cleanup, cant have player names rather have only numerical values, drop unneccessary data columns

In [ ]:
df = df.drop(columns=['PLAYER', 'CS'])

In [ ]:
df.head()

YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA  \
0   24  3035  11434  2246  4189  724  295  117   726  1249   357  892  0.366   
1   22  3026  10972  1949  3630  725  177  475  1951  1599   696   78  0.331   
2   22  2789  10195  1882  3514  792  222  117   724  1381   220  432  0.345   
3   20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358  0.310   
4   21  2792  10430  1736  3430  640  252  101     0   963   327  722  0.329   

   HOF  
0    1  
1    1  
2    1  
3    1  
4    1

In [ ]:
# separate into x features and y outcome
# what causes for someone to be in the hall of fame?
# y = hall of fame
# x =

X = df.iloc[:,0:13]

In [ ]:
y = df.iloc[:,13]

In [ ]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=11, test_size=0.2)

In [ ]:
# add in a scaler
scaler = MinMaxScaler(feature_range=(0,1))

In [ ]:
# fit data into scaler
X_train = scaler.fit_transform(X_train)

In [ ]:
X_test = scaler.fit_transform(X_test)

In [ ]:
# add in knn
knn = KNeighborsClassifier(n_neighbors=8)

In [ ]:
# fit data into model
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [ ]:
# make some predictions
y_pred = knn.predict(X_test)

In [ ]:
print(y_pred)

[0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0
 0 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0
 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1]


In [ ]:
knn.score(X_test, y_test)

0.8279569892473119

In [ ]:
# reporting: confusion matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
print(cm)

# top left: true positive
# bottom right: true negative
# top right: false positive
# bottom left: false negative

[[55 12]
 [ 4 22]]


In [ ]:
cr = classification_report(y_test, y_pred)

In [ ]:
print(cr)

# precision
# 55/59 = 0.93

# recall
# true pos/(trpos+false pos), 55/(55+12) = 0.82

# f1-score
# 2*0.93* = 1.525
# 0.93+0.83 = 1.75
# 1.525/1.75 = 0.87

# support
# 55 + 12 = 67
# 4 + 22 = 26

# also took out outliers
# 0.93 + 0.65 / 2 = 0.79 = macro avg precision


              precision    recall  f1-score   support

           0       0.93      0.82      0.87        67
           1       0.65      0.85      0.73        26

    accuracy                           0.83        93
   macro avg       0.79      0.83      0.80        93
weighted avg       0.85      0.83      0.83        93



In [ ]:
print(knn.n_samples_fit_)
# 372+93 = 465

372


# Decision Tree
- flow chart
- supervised learning, prelabeled data
- split data based on different criteria based on flow charts